### PR TITLE
Fix time conversion with daylight savings

### LINKED ISSUE #369: Time parsing tests fail when localtime is in Daylight Savings
The seven asserts in the unit tests that depend on time parsing fail by being off by one hour, when localtime is in daylight savings time.  These test will pass when local time is set to January, when daylight savings in not in effect, or location set to Phoenix, which doesn't have a daylight savings.  I would suppose using UTC would also work.

A quick check of the code seems to be around rss/rss_parser.cpp:118, where some variables reference PST (Pacific Standard) and others have PDT (Pacific Daylight).  I'll have to look more closely to determine what assumptions the different functions are making.

[datetestresults.txt](https://github.com/akrennmair/newsbeuter/files/504542/datetestresults.txt)

### PR DESCRIPTION
**Pull request by orner**
Fixes #369

### CODE REVIEW

File: test/rss.cpp [hunk 1]
```diff
@@ -154,6 +154,41 @@ TEST_CASE("W3CDTF parser behaves correctly") {
...
 	}
 
+	// There has been a problem in the C date conversion functions when the TZ is
+	// set to different locations, and localtime is in daylight savings. One of
+	// these two next tests should be in active daylight savings
+	SECTION("W3CDTF with -08:00 timezone Pacific") {
+		setenv("TZ", "US/Pacific", 1);
+		tzset();
+		REQUIRE(rsspp::rss_parser::__w3cdtf_to_rfc822("2008-12-30T10:03:15-08:00") == "Tue, 30 Dec 2008 18:03:15 +0000");
+		unsetenv("TZ");
```
Comment (Minoru) [inline test/rss.cpp]: I think tests should *preserve* the environment, not clear it, because clearing prevents us from passing `TZ` from the outside to the tests that happen to run after this one. So instead of unsetting `TZ`, please set it back to whatever value it previously had.

You can also DRY this block of tests by using so-called "sections" that our testing framework provides. Take a look at [a test](https://github.com/akrennmair/newsbeuter/blob/b6383a64cdfed333e2e31a33f908b33dd42ae3da/test/textformatter.cpp#L95-L119) that already uses them, and also [the framework's docs](https://github.com/philsquared/Catch/blob/master/docs/tutorial.md#test-cases-and-sections).

**Comment by Minoru** [comment]
Ah, one more thing: to close the issue when the PR is merged, the words "Fixes #abc" should appear in the commit message, not just PR's text. See [the relevant GitHub help page](https://help.github.com/articles/closing-issues-via-commit-messages/) for details. (You can amend the commit, or I'll just close the issue via a merge commit; no big deal.)

File: test/rss.cpp (hunk 1 above)
Comment (orner) [inline test/rss.cpp]: Thanks.  I added the comments as requested, and move these tests into their own test case with test sections, so the setting and reset of the TZ variable can be done properly.

File: rss/rss_parser.cpp [hunk 2]
```diff
@@ -113,11 +113,12 @@ std::string rss_parser::__w3cdtf_to_rfc822(const std::string& w3cdtf) {
 		}
 	}
 
-	time_t t = mktime(&stm);
-	time_t x = time(NULL);
-	t += localtime(&x)->tm_gmtoff + offs;
+	//tm_isdst will force mktime to consider DST, like localtime(), but
+	//then the offset will be zeroed out, since that was manually added
```
Comment (orner) [inline rss/rss_parser.cpp]: The old solution used the tm_gmtoff member, which apparently is not part of the standard, but part of BSD.  I had one solution that set that value manually, but that broke on the Apple builds.  The solution that's there now doesn't use that member variable.

**Comment by orner** [comment]
Hmm, the build seem to die.  How do you restart it?  I don't see a build issue here.

File: test/rss.cpp [hunk 3]
```diff
@@ -166,3 +166,43 @@ TEST_CASE("W3CDTF parser behaves correctly") {
 		REQUIRE(rsspp::rss_parser::__w3cdtf_to_rfc822("") == "");
 	}
 }
+
+TEST_CASE("W3CDTF behaves correctly with different local timezones") {
```
Comment (Minoru) [inline test/rss.cpp]: I must've missed that on the first review; sorry about that. I think this line should say "W3C DTF to RFC 822 conversion", not just "W3CDTF", because, well, time format doesn't have a behaviour—it's a static thing, right?

File: test/rss.cpp [hunk 4]
```diff
@@ -166,3 +166,43 @@ TEST_CASE("W3CDTF parser behaves correctly") {
...
+	// There has been a problem in the C date conversion functions when the TZ is
+	// set to different locations, and localtime is in daylight savings. One of
+	// these two next tests sections should be in active daylight savings.
+	// https://github.com/akrennmair/newsbeuter/issues/369
+	
+	char *tz = getenv("TZ");
```
Comment (Minoru) [inline test/rss.cpp]: My manpage on `getenv` says:

> The string pointed to by the return value of getenv() may be statically allocated, and can be modified by a subsequent call to getenv(), putenv(3), setenv(3), or unsetenv(3).

So I'd rather you immediately copy the value to a safe place that you allocated yourself. Stack-allocated array of large enough size should do just fine, I guess.

File: test/rss.cpp [hunk 5]
```diff
@@ -166,3 +166,43 @@ TEST_CASE("W3CDTF parser behaves correctly") {
...
+	}
+
+	SECTION("Timezone UTC") {
+		setenv("TZ", "UTC", 1);
+		tzset();
+		REQUIRE(rsspp::rss_parser::__w3cdtf_to_rfc822("2008-12-30T10:03:15-08:00") == "Tue, 30 Dec 2008 18:03:15 +0000");
+	}
+
+	// Reset back to original value
+	if (tz)
```
Comment (Minoru) [inline test/rss.cpp]: Let's not omit the curly brackets. Better be safe than sorry.

**Comment by Minoru** [comment]
> Hmm, the build seem to die. How do you restart it?

I think you'll need a push access to do that.

> I don't see a build issue here.

Indeed there's none. You can click on the red cross mark next to a commit to get a list of checks. From there, you will be able to see that for your latest commit, the build passed, but Coveralls (test coverage reporting service) failed because of a slight decrease in coverage. I'm ignoring this because the fluctuation is small and probably comes from optimizations done by the compilers.

**Comment by orner** [comment]
One of the builds on the Mac looked like it stopped for no reason, failing the CI testing.  I didn't know how to manually restart it, so I pushed another empty commit, and that relaunched the job.

I'll make the changes suggested later today.

Also, it looks like the style here is to keep amending the previous commit, and I'll do that.  Or, should I be putting new changes in separate commits?

**Comment by Minoru** [comment]
> One of the builds on the Mac looked like it stopped for no reason

Ah, I see. Travis has been having some issues with OS X workers for the past week or so.

> Also, it looks like the style here is to keep amending the previous commit, and I'll do that. Or, should I be putting new changes in separate commits?

Amending is just what I personally do. Newsbeuter doesn't get that many contributions, so I'll accept your changes regardless of the way you shape the history :)

**Comment by Minoru** [comment]
Thanks for your work!

**Comment by orner** [comment]
No problem.  I might keep poking at this code as I have time.  I'm starting to figure out how everything works now.  :)
