### PR TITLE
Check for iconv() TRANSLIT support

### LINKED ISSUE #174: compile issues under musl-libc
Hi,

Had to do the following to make it work in AlpineLinux (musl-libc based).
https://gist.github.com/insteps/da095c4cf032ce8ba80c

Musl-libc, has its own iconv, 
but presently does not  have any //TRANSLIT implementations.

This may not be an elegant solution,
but any better changes if possible would be nice.

Regards.

### LINKED ISSUE #364: STFL Parser error near '' with musl-libc
Janko on IRC reported this.

When converting forms to STFL's internal widechar representation, we specify `//TRANSLIT` to ensure that as many users as possible see something meaningful in place of characters that their locale encoding can't represent. However, musl [doesn't implement transliteration](http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc#iconv), causing Newsbeuter to crash with `STFL Parser error near ''`. ([The call](https://github.com/akrennmair/newsbeuter/blob/master/src/stflpp.cpp#L23) to `stfl_ipool_towc` returns empty string.)

Three solutions were proposed:
1. Remove `//TRANSLIT` altogether. The world moved on, new systems use UTF-8 (but we didn't find any statistics on that).
2. Use `#ifdef`s to figure out what libc we're dealing with, decide to include `//TRANSLIT` based on that. There's a slight problem there: musl [doesn't define any macro](http://wiki.musl-libc.org/wiki/FAQ#Q:_why_is_there_no_MUSL_macro_.3F). We'll have to do it autoconf-style: compile a testing binary, run it, look at the exit code and figure out things from there.
3. Do runtime check to see if `//TRANSLIT` results in `stfl_ipool_towc` returning empty string. If so, don't use `//TRANSLIT` anymore.

Since the problem depends on libc, i.e. something that doesn't change at runtime, the third option is out.

Out of the first two, the first is the best maintainability-wise, but will break things for people who run Newsbeuter on older systems with non-Unicode locales. Thus it looks like we'll have to go with option 2.

Implementation might proceed as follows:
- [ ] write a small C++ program that will check if `//TRANSLIT` is necessary (with glibc it's used to avoid errors on unmappable chars). The result should be returned via exit code.
- [ ] edit `config.sh` to compile and run the test program. Depending on the result, some flag shall be put into `config.mk` (see how `DEFINES` is used in `check_ssl_implementation()`).
- [ ] edit all the places where `//TRANSLIT` is used so that `//TRANSLIT` is excluded if there's no support from libraries.
- [ ] try and test it on other platforms, including Linux with glibc and some BSD systems (just to make sure nothing was broken).

### PR DESCRIPTION
**Pull request by kobezda**
Some iconv() implementations don't support transliteration.
When iconv with //TRANSLIT is first attempted and fails,
try again without it, and remember the result.

Fixes #364
Fixes #174

### CODE REVIEW

File: src/stflpp.cpp [hunk 1]
```diff
@@ -16,7 +17,7 @@ namespace newsbeuter {
  */
 
 stfl::form::form(const std::string& text) : f(0) {
-	ipool = stfl_ipool_create((std::string(nl_langinfo(CODESET)) + "//TRANSLIT").c_str());
+	ipool = stfl_ipool_create(utils::translit(std::string(nl_langinfo(CODESET)), "WCHAR_T").c_str());
```
Comment (Minoru) [inline src/stflpp.cpp]: We can encapsulate some string conversion if we add `std::string translit(const char* tocode, const std::string& fromcode)`.

(There's also final `c_str()` call, but I suspect this is more tricky due to time of life details. I'll deal with this myself later.)

**Comment by Minoru** [comment]
We don't have any tests for that part of Newsbeuter, so it's a bit early to call it a day.

Checklist of things I want to do before merging this:
- [ ] build on FreeBSD, check if anything breaks
- [ ] install on my machine, see if anything changes (I have UTF-8 locale so nothing should change for me)

If both of these checks fail to find any problems, I'm going to merge this PR on Sunday, October 1st.

@kobezda, thanks for your work!

**Comment by Minoru** [comment]
Well, my testing didn't find any problems, so hopefully our users won't run into any either. Thanks, @kobezda!
